name: chefbot
version: 1.0.0
github: "distributive/chefbot"
license: MIT
author: "distributive"
maintainer: "github.com/distributive"
copyright: "2022 distributive"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/distributive/ChefBot#readme>

dependencies:
  - base >= 4.7 && < 5
  - extra
  - discord-haskell
  - emoji
  - text
  - text-icu
  - text-regex-replace
  - transformers
  - load-env
  - megaparsec
  - persistent
  - persistent-sqlite
  - persistent-template
  - random
  - esqueleto
  - monad-logger
  - time
  - aeson
  - bytestring
  - yaml
  - http-conduit
  - raw-strings-qq
  - template-haskell
  - timezone-olson
  - unordered-containers
  - bytestring
  - req
  - http-client
  - data-default
  - exception-transformers
  - resourcet
  - resource-pool
  - containers
  - th-printf
  - mtl
  - safe
  - edit-distance
  - unliftio
  - process
  - split
  - regex-pcre
  - distribution
  - scientific >= 0.3.7.0

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - LambdaCase
    - EmptyDataDecls
    - FlexibleContexts
    - GADTs
    - GeneralizedNewtypeDeriving
    - MultiParamTypeClasses
    - QuasiQuotes
    - TemplateHaskell
    - TypeFamilies
    - DerivingStrategies
    - StandaloneDeriving
    - UndecidableInstances
    - DataKinds
    - FlexibleInstances
    - DeriveGeneric
    - TypeApplications
    - MultiWayIf
    - TupleSections
    - ConstraintKinds
    - RecordWildCards
    - ScopedTypeVariables
    - TypeOperators
    - RankNTypes
    - BangPatterns
  ghc-options:
    - -Wall

executables:
  ChefBot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chefbot

tests:
  ChefBot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chefbot
